### PR TITLE
Promote Gleb Reznicov to Intermediate Developer

### PR DESCRIPTION
**Pull request by sukh-gill**
**What kind of change does this PR introduce?** (check at least one)

- [X] Feature (non-breaking change which adds functionality)

**Does this PR introduce a breaking change?** (check one)

- [X] No

**Did you test your solution?**

- [X] Leveled as developer ON-Stack & OFF-Stack
- [X] Helped support Serverless Development
- [X] Developed projects both as an FE & BE 
- [X] Supporting new incoming developers

## Problem Description

The dev team has been growing, and with the advanced technical solutions Jam 3 creates, we need more seasoned Developers to support our incoming devs to help elevate their technical knowledge.

## Solution Description

# Gleb Reznicov to Intermediate Developer 🎓 #

Gleb has been with Jam for two years and has jumped on a wide variety of projects from off stack to on-stack, taking on all challenges that came his way. He has supported his fellow devs on projects like St-Micheals, Toyota, EA Nascar, CultureCon, supporting FE & BE development, and I can't forget his serverless contribution to Specto. He now has moved over to the on-stack world to grow his skill sets as a nimble & flexible developer who could support across all Jam 3 stacks.

This promotion is well deserved & earned, and excited to see how Gleb shines as an Intermediate developer.

## Side Effects, Risks, Impact

- No Risks
- Gleb will be supporting the FB Team through its growth

**Additional comments:**
I couldn't be more excited for this promotion as Gleb is my first report & we both joined Jam 3 simultaneously. It's been a pleasure to watch his growth from a Co-op -> Junior Dev -> Intermediate Dev. You've been fully integrated into Jam3 and became an awesome dev, teammate, and friend to so many. Congrats, and I can't wait to see how you evolve from here.

### CODE REVIEW

**Comment by notbrian** [comment]
Yay, congrats Gleb!!

**Review by PeterAltamirano — APPROVED** [review]
giphy

Awesome to see you grow Gleb 🚀 🚀 🚀 BIG CONGRATS! Approved!

**Comment by alemesa** [comment]
Congrats Gleb, my man 🚀 🔥  !!!! very well deserved

**Review by alemesa — APPROVED** [review]

**Comment by jslim** [comment]
Gleboooo!! congrats man!!, so well deserved!! 🚀 🚀

**Comment by alastairodhiambo** [comment]
Congrats Gleb!! 🎉 🚀 🚀  You taught me so much on CultureCon!

**Comment by rodrigo-techera** [comment]
Congrats Gleb! I had the opportunity to see you from the start and you already looked like a star 🚀  keep going!

**Comment by miguelmoraleda** [comment]
Congratulations Gleb! Well deserved!

**Comment by neo** [comment]
Gleb! Congratulations!! 🎉 

Now that I really think about it, I actually haven't really worked with you on a full project yet, but I can always feel your effort, your work and your value in so many ways! Very well deserved!!

**Comment by namniak** [comment]
Congrats Gleb! So well deserved. Love working with you.
Keep it uppppp 🚀

**Pull request merged**
